### ISSUE TITLE
Not sure about ALB context here...

### ISSUE THREAD

**Issue by archenroot** [trussworks/terraform-aws-waf#12]
Hello,

I though WAF is something to be put infront of either regular web or api request, once it goes trough waf it will hit either api gateway or cloudfront.

Let say our deployment is more like:
web:
WAF -> Cloudfront -> api gateway -> ALB -> ECS -> FARGATE
api access:
WAF -> API Gateway -> ALB -> ECS -> FARGATE

So what does that mean linking WAF with ALB in this project, what is the use case for it?

**Comment by dynamike** [comment]
The cases we've used it up to this point didn't have an API Gateway. So the most similar use case to what you have is API Access and looks like
WAF -> ALB -> Fargate

I'm curious to understand your usage of the API Gateway.

**Comment by archenroot** [comment]
Well API Gateway can handle few things for you:
- Authentication with OneLogin/OnePassport and Cognito integration, receive Authorization being forwarded to ECS Fargate real Backend API
- You can check what access type you receive (internal vs external for example) and provide different endpoint exposure to those access zones
