### ISSUE TITLE
Error: WAFDisallowedNameException: The specified name is not permitted.

### ISSUE THREAD

**Issue by ismail0352** [trussworks/terraform-aws-waf#25]
Getting this error when using this module.

**Comment by dynamike** [comment]
Can you add a little more detail about how you are using the module?

**Comment by ismail0352** [comment]
I don't know how but tried it this morning. And it works.

**Comment by ismail0352** [comment]
I am reopening this issue. 
Today morning I got it. I am not sure the reason why it is happening, but here the code that I am using.

```
module "waf" {
  source = "github.com/trussworks/terraform-aws-waf"
  alb_arn                                         = module.alb.this_lb_arn
  associate_alb                               = true
  blocked_path_prefixes                 = ["/admin", "/password"]
  allowed_hosts                              = ["apples", "oranges"]
  wafregional_rule_f5_id                 = "" 
  web_acl_metric_name                 = "prod_alb_acl_metric_name"
  web_acl_name                             = "prod_alb_acl"
}
```

Here is the error message received:
`Error: WAFDisallowedNameException: The specified name is not permitted.

  on .terraform/modules/waf/main.tf line 46, in resource "aws_wafregional_rule" "allowed_hosts":
  46: resource "aws_wafregional_rule" "allowed_hosts" {



Error: WAFDisallowedNameException: The specified name is not permitted.

  on .terraform/modules/waf/main.tf line 81, in resource "aws_wafregional_rule" "blocked_path_prefixes":
  81: resource "aws_wafregional_rule" "blocked_path_prefixes" {

`

**Comment by dynamike** [comment]
This is likely due to the character requirements in the web_acl_name. They don't allow `_`
